path:
  data: /data
  logs: /var/lib/elasticsearch/log
  plugins: /var/lib/elasticsearch/plugins
  work: /var/lib/elasticsearch/work
cluster:
  name: felmas
# Set up CORS for read-only access
http.cors.enabled: true
http.cors.allow-origin: *